[versions]
agp = "8.2.0"
kotlin = "1.9.21"
compose = "1.5.11"
kotlinx-serialization-json = "1.6.2"
compose-compiler = "1.5.6"
activity-compose = "1.8.1"
navigation-compose = "2.7.5"
kotlinx-coroutines = "1.8.0-RC"
appcompat = "1.6.1"
android-lifecycle = "2.2.0"
play-services-location = "21.0.1"
compose-material3 = "1.1.2"
androidx-activityCompose = "1.8.1"
sqlDelight = "2.0.1"
ktor = "2.3.6"
logback-classic = "1.2.11"
touchlab = "2.0.5"
koin = "3.5.2-RC1"
mvi = "3.3.0"
decompose = "2.2.0-compose-experimental-beta02"
essenty = "1.3.0"
calfUi = "ee38302d42"
calf = "0.3.0"
image-loader = "1.7.1"

android-minSdk = "24"
android-compileSdk = "34"
code = "1"
major = "1"
minor = "0"
patch = "0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "android-lifecycle" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-javafx = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-javafx", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

sqldelight-driver-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
sqldelight-driver-sqlite = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
sqldelight-driver-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
sqldelight-driver-sqljs = { module = "app.cash.sqldelight:sqljs-driver", version.ref = "sqlDelight" }
sqldelight-extensions-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqldelight-adapters-primitive = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqlDelight" }

arkivanov-mvi = {module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mvi" }
arkivanov-mvi-main = {module = "com.arkivanov.mvikotlin:mvikotlin-main", version.ref = "mvi" }
arkivanov-mvi-coroutines = {module = "com.arkivanov.mvikotlin:mvikotlin-extensions-coroutines", version.ref = "mvi" }
arkivanov-decompose = {module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
arkivanov-decompose-compose = {module = "com.arkivanov.decompose:extensions-compose-jetbrains", version.ref = "decompose" }
arkivanov-essenty-lifecycle = {module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }

ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-resources = { module = "io.ktor:ktor-client-resources", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }

logback-logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }
touchlab-stately-common = { module = "co.touchlab:stately-common", version.ref = "touchlab" }

#calf-ui = { module = "com.mohamedrejeb.calf:calf-ui", version.ref = "calf" }
#calf-ui = { module = "com.github.Shahriyar13:calf", version.ref = "calfUi" }
calf-file-picker = { module = "com.mohamedrejeb.calf:calf-file-picker", version.ref = "calf" }

image-loader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "image-loader" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
sqlDelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
